# Generated by Django 6.0.6 on 2026-06-09 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='nip',
            new_name='niy',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='tanggal_bergabung',
            new_name='tanggal_masuk',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status_aktif',
        ),
        migrations.AddField(
            model_name='employee',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_karyawan',
            field=models.CharField(choices=[('Tetap', 'Karyawan Tetap'), ('Kontrak', 'Karyawan Kontrak'), ('Percobaan', 'Masa Percobaan (Probation)')], default='Tetap', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr.position'),
            preserve_default=False,
        ),
    ]
