# Generated by Django 6.0.6 on 2026-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='deskripsi_potongan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_potongan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status_karyawan',
            field=models.CharField(choices=[('Tetap', 'Karyawan Tetap'), ('Contrak', 'Karyawan Kontrak'), ('Percobaan', 'Masa Percobaan (Probation)')], default='Tetap', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='tipe',
            field=models.CharField(max_length=20),
        ),
    ]
