# Generated by Django 6.0.6 on 2026-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_payroll_deskripsi_potongan_payroll_total_potongan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertunjangan',
            name='jenis_tunjangan',
            field=models.CharField(choices=[('Tetap', 'Tunjangan Tetap (Otomatis 100%)'), ('Variabel', 'Tunjangan Variabel (Berbasis KPI)')], default='Variabel', max_length=20),
        ),
    ]
