# Generated by Django 6.0.6 on 2026-06-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rename_nip_employee_niy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gaji_pokok',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
