# Generated by Django 6.0.6 on 2026-06-09 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_gaji_pokok'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianKinerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('tahun', models.IntegerField()),
                ('total_skor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final (Terkunci)')], default='Draft', max_length=20)),
                ('tanggal_dinilai', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_penilaian', to='hr.employee')),
            ],
            options={
                'unique_together': {('employee', 'bulan', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='DetailPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_mentah', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skor_berbobot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kriteria_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.kpicriteria')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hr.penilaiankinerja')),
            ],
        ),
    ]
