# Generated by Django 6.0.6 on 2026-06-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_penilaiankinerja_detailpenilaian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaiankinerja',
            name='status',
        ),
        migrations.AddField(
            model_name='penilaiankinerja',
            name='grade_akhir',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='penilaiankinerja',
            name='tanggal_dinilai',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
