# Generated by Django 6.0.6 on 2026-06-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_penilaiankinerja_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'bulan', 'tahun')},
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='salary_component',
        ),
        migrations.AddField(
            model_name='payroll',
            name='bulan',
            field=models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='hari_alpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tahun',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tunjangan_jabatan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='nama_bonus',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gaji_bersih',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gaji_pokok',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Selesai', 'Selesai')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_potongan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='nominal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_details', to='hr.payroll'),
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='period',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_tunjangan',
        ),
    ]
