# Generated by Django 6.0.6 on 2026-06-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_payroll_period_remove_payroll_total_tunjangan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'bulan', 'tahun')},
        ),
    ]
